# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py
sudo: required

services:
  - docker

language: python
python:
  - "3.5"
  - "3.6"

install:
  - "pip install -r requirements.txt"
  - "pip install -r requirements_dev.txt"
  - "flake8 mikulov"
  - "python setup.py build"

script: "python setup.py test"

after_success:
  - if [[ "$TRAVIS_BRANCH" == "master" && "$TRAVIS_PULL_REQUEST" == "false" && "$TRAVIS_PYTHON_VERSION" == "3.6" ]]; then
    docker build -t vrutkovs/mikulov . &&
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" &&
    docker push vrutkovs/mikulov;
    fi

deploy:
  on:
    tags: true
    repo: vrutkovs/mikulov
    condition: $TRAVIS_PYTHON_VERSION == "3.6"
